config/routes.rb
Rails.application.routes.draw do

  resources :players do
    collection do
      get 'position_search'
      get 'location_search'
    end
  end

  resources :stats
  resources :player_stats

  root "home#index"

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :accounts, only: [:new, :create, :update] do
    resources :notifications
  end
  resources :position_needs, only: [:create, :destroy]

  resources :schools, only: [:index, :show, :new, :create] do
    collection do
      get 'position_needs_search'
      get 'location_search'
    end
  end

  resources :favorite_schools, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: :index

  resources :videos

  post "/panda/authorize_upload", :to => "panda#authorize_upload"
  post "/panda/authorize_upload_postprocess", :to => "panda#authorize_upload_postprocess"
  get "/new_video", :to => "videos#simple"
  get "/new_video/advanced", :to => "videos#advanced"
  post "/videos/postprocess", :to => "videos#postprocess"

end

app/models/notification.rb
class Notification < ActiveRecord::Base

  include Workflow

  workflow do
    state :new do
      event :review, transitions_to: :reviewed
    end
    state :reviewed
  end

  belongs_to :account
  belongs_to :notifieable, polymorphic: true

  after_create :new_notification

  attr_accessor :mark_reviewed
  scope :active, -> { with_new_state }

  def new_notification
  end

  def load_notifieable
    id = self.notifieable_id
    resource = self.notifieable_type.constantize
    resource.find(id)
  end

  def active
    notifications.with_new_state
  end

  def self.mark_reviewed(type, notifieable_id, current_user_id)
    @user = Account.find(current_user_id)
    @notes = @user.notifications.active
    @notes.each do |note|
      case type
      when "school"
        if note.notifieable.school.id == notifieable_id.to_i
          note.review!
          note.save
        end
      when "player"
        if note.notifieable.player.id == notifieable_id.to_i
          note.review!
          note.save
        end
      end
    end
  end

  

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def new
  end

  def create
    @notification = Notification.new(notification_params)
    if @notification.save
      redirect_to :back
    end
  end

  def index
    @notifications = current_user.notifications
  end

  def show
  end

  def destroy
  end

  private

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_account_notifications.html.haml
%div.modal.fade#notifications-modal{"tabindex" => "-1", role: "dialog", "aria-labelledby" => "notifications-label", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h4.modal-title#notifications-label
          Your Notifications
      %div.modal-body
        - if @account.notifications.active.empty?
          %strong You don't have any new notifications!
          = link_to "Check out your old ones", account_notifications_path(@account)
        %ul
          = render @account.notifications.active.order(created_at: :asc)
      %div.modal-footer
        %button.btn.btn-default{ type: "button", "data-dismiss" => "modal"}
          Close

app/views/notifications/_notification.html.haml
- case notification.notifieable_type
  - when "FavoriteSchool"
    %li= link_to "Your school was favorited by #{notification.notifieable.player.first_name} #{distance_of_time_in_words(Date.today, notification.created_at)} ago.", notification.notifieable.player
  - when "PositionNeed"
    %li= link_to "#{notification.notifieable.school.name} has added #{notification.notifieable.position.abbreviation.upcase} to their needs #{distance_of_time_in_words(Date.today, notification.created_at)} ago.", notification.notifieable.school

app/views/notifications/index.html.haml
%br
- if @notifications.empty?
  %strong You don't have any notifications!
%ul{style: "list-style:none;"}
  = render @notifications.order(created_at: :asc)