config/routes.rb
Rails.application.routes.draw do

  resources :players do
    collection do
      get 'position_search'
      get 'location_search'
    end
  end

  resources :stats
  resources :player_stats

  root "home#index"

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :accounts, only: [:new, :create, :update] do
    resources :notifications
  end
  resources :position_needs, only: [:create, :destroy]

  resources :schools, only: [:index, :show, :new, :create] do
    collection do
      get 'position_needs_search'
      get 'location_search'
    end
  end

  resources :favorite_schools, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: :index

  resources :videos

  post "/panda/authorize_upload", :to => "panda#authorize_upload"
  post "/panda/authorize_upload_postprocess", :to => "panda#authorize_upload_postprocess"
  get "/new_video", :to => "videos#simple"
  get "/new_video/advanced", :to => "videos#advanced"
  post "/videos/postprocess", :to => "videos#postprocess"

end

app/models/school.rb
class School < ActiveRecord::Base

  has_one :account, as: :accountable
  has_many :position_needs
  has_many :favorite_schools
  has_many :positions, through: :position_needs
  has_many :sports, through: :positions

  accepts_nested_attributes_for :account

  def favorited(player)
    @current = []
    favorite_schools.each do |fav|
      @current.push(fav.player)
    end
    @current.include?(player)
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  before_action :set_school, only: [:show, :edit, :update]
  skip_filter :ensure_logged_in, only: [:new, :create]

  def index
    @schools = School.all
  end

  def new
    @school = School.new
    @school.build_account
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to root_path
    else
      render :new, notice: "Oops, there was an error."
    end
  end

  def show
    Notification.mark_reviewed("school", params[:id], current_user.id)
  end

  def location_search
    location = params[:location]
    @schools = School.joins(:account).where("accounts.location = ?", location)
    render :index
  end

  def position_needs_search
    position = params[:position]
    @schools = School.joins(:positions).where("positions.name = ?", position)
    render :index
  end

  private

  def set_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :web_url, account_attributes: [ :email, :password, :password_confirmation, :location, :about, :avatar, :terms, :accountable_id, :accountable_type ] )
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper

  def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end


end

app/views/schools/_form.html.haml
.form-group
  = f.label :name
  = f.text_field :name, class: "form-control"
%br
.form-group
  = f.label "A link to your website"
  = f.text_field :web_url, class: "form-control"
%br
= f.fields_for :account do |ff|
  = ff.hidden_field :active, value: true
  .form-group
    = ff.label "Say something about yourself"
    = ff.text_area :about, class: "form-control"
  %br
  .form-group
    = ff.label "Where are you from?"
    = select_tag "school[account_attributes][location]", options_for_select(us_states), class: "form-control"
  %br
  .form-group
    = ff.label :email
    = ff.email_field :email, class: "form-control"
  %br
  .form-group
    = ff.label :password
    = ff.password_field :password, class: "form-control"
  %br
  .form-group
    = ff.label :password_confirmation
    = ff.password_field :password_confirmation, class: "form-control"
  .form-group
    Give a good first impression, upload a photo.
    = ff.file_field :avatar
  %br
  - unless current_user
    .checkbox
      %label
        = check_box_tag :terms
        Do you agree to our terms and conditions?
%hr
  = link_to "Cancel", login_path, class: "btn btn-default"
  = f.submit "Save", class: "btn btn-default"

app/views/schools/_school_home.html.haml
%br
%legend Home
.col-md-6
  .panel.panel-default
    .panel-body
      .row
        .col-xs-12.col-sm-8
          %h2= "#{school.name.titleize}"
          %p
            Location
            %strong= school.account.location.upcase
          %p
            %strong Needs:
            - school.position_needs.each do |need|
              %a.pos-pop{rel: "popover", "data-html"=>"true","data-container"=>"body", "data-content"=>"#{link_to 'Find Players', players_path, 'class'=>'btn btn-default btn-xs'} #{link_to "Delete Need", need, 'method'=>'delete', 'class'=>'btn btn-default btn-xs'}", "data-placement"=>"left","data-toggle"=>"popover", id: "pos-pop-#{need.id}"}
                %span.label.label-info.tags= need.position.abbreviation.upcase
        .col-xs-12.col-sm-4.text-center
          %img.center-block.img-circle.img-responsive{alt: "", src: @account.avatar.url}
      .row
        .col-xs-12.col-sm-4
          %h2
            %strong= @account.notifications.active.count
          %p
            %small Notifications
        .col-xs-12.col-sm-4
          %h2
            %strong= school.position_needs.count
          %p
            %small Needs
        .col-xs-12.col-sm-4
          %h2
            %strong 0
          %p
            %small New Messages
      .row
        .col-xs-18.col-sm-6
          %a{href: "#", style: "color:#029ece;", "data-toggle" => "modal", "data-target" => "#new-position_need-modal", id: "new-position_need"}
            %button.btn.btn-default.btn-block
              New Need
        .col-xs-18.col-sm-6
          %a{href: "#", style: "color:#029ece;", "data-toggle" => "modal", "data-target" => "#notifications-modal", id: "notifications"}
            %button.btn.btn-default.btn-block
              Notifications

= render "position_needs/new", account: @account

= render "notifications/account_notifications", account: @account

app/views/schools/index.html.haml
.row
  %br
  %h3
    %strong Find:
    %a{href: schools_path}
      All
    - Position.all.each do |pos|
      = link_to "#{pos.abbreviation.upcase}", "/schools/position_needs_search?position=#{pos.name}"
%table.table.table-hover#schools
  %thead
    %tr
      %th Name
      %th Location
      %th Sport
      %th Needs
  %tbody
    - @schools.each do |school|
      %tr.primary
        %td= link_to "#{school.name.titleize}", school
        %td
          %p{syle: "color:black;"}
          = link_to "#{school.account.location.upcase}", "/schools/location_search?location=#{school.account.location}"
        %td
          - school.sports.uniq.each do |sport|
            %p= sport.name.titleize
        %td
          - school.position_needs.each do |need|
            %p= need.position.name.titleize

app/views/schools/new.html.haml
%br
= form_for @school do |f|
  = render "form", f:f

app/views/schools/show.html.haml
%br
.row
  .col-md-10
    %h1= @school.name.titleize
  .col-md-2
    - if @school.favorited(current_user.accountable)
      %button.btn.btn-sm.btn-default.disabled
        Favorited
    - else
      %a.navbar-right{href: "#", style: "color:#029ece;", "data-toggle" => "modal", "data-target" => "#new-favorite_school-modal", id: "new-favorite_school"}
        %button.btn.btn-sm.btn-default
          Favorite
%hr
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        .row
          / /col
          .col-xs-12.col-sm-4.text-center
            - if @school.account.avatar.present?
              %img.center-block.img-responsive{alt: "", src: @school.account.avatar.url}
          .col-xs-18.col-sm-6
        .row
          .col-xs-12.col-sm-4
            %h2
              %strong= @school.position_needs.count
            %p
              %small Needs
          .col-xs-12.col-sm-4
            %h2
              %strong= @school.favorite_schools.count
            %p
              %small Favorited
          .col-xs-12.col-sm-4
            %h2
              %strong= @school.account.location.upcase
            %p
              %small Location
        .row
          .col-xs-12.col-sm-8
            %p
              %strong Needs:
              - @school.position_needs.each do |need|
                %span.label.label-info.tags= need.position.abbreviation.upcase
  .col-md-1
  .col-md-5
    .panel.panel-default#interested-players
      .panel-body
        %legend
          %small Interested Players
        %table.table.table-striped
          %thead
            %th Position
            %th Player
          %tbody
            - @school.favorite_schools.each do |favorite|
              %tr
                %td
                  %p
                    - favorite.player.positions.each do |pos|
                      = pos.abbreviation.upcase
                %td= favorite.player.first_name
.row
  .col-md-12
    .panel.panel-default#school-description
      .panel-body
        %legend= "About #{@school.name.titleize}"
        %p= @school.account.about

%div.modal.fade#new-favorite_school-modal{"tabindex" => "-1", role: "dialog", "aria-labelledby" => "new-favorite_school-label", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h4.modal-title#new-favorite_school-label
          Add Favorite?
      %div.modal-body
        = form_for FavoriteSchool.new do |f|
          = render "favorite_schools/form", f:f