config/routes.rb
Rails.application.routes.draw do

  resources :players do
    collection do
      get 'position_search'
      get 'location_search'
    end
  end

  resources :stats
  resources :player_stats

  root "home#index"

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :accounts, only: [:new, :create, :update] do
    resources :notifications
  end
  resources :position_needs, only: [:create, :destroy]

  resources :schools, only: [:index, :show, :new, :create] do
    collection do
      get 'position_needs_search'
      get 'location_search'
    end
  end

  resources :favorite_schools, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :home, only: :index

  resources :videos

  post "/panda/authorize_upload", :to => "panda#authorize_upload"
  post "/panda/authorize_upload_postprocess", :to => "panda#authorize_upload_postprocess"
  get "/new_video", :to => "videos#simple"
  get "/new_video/advanced", :to => "videos#advanced"
  post "/videos/postprocess", :to => "videos#postprocess"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title recruit.me
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{src: "//cdn.pandastream.com/u/2.1/panda-uploader.min.js"}
  %body
    .navbar-wrapper
      .navbar.navbar-default.navbar-fixed-top{role: "navigation"}
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only recruit.me
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "/"}
            %span.icon-VeloMark{"data-icon" => "logo.ico"}
            %span.logo recruit.me
        .collapse.navbar-collapse#navbar-collapse-1
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li
                %a.active{href: account_notifications_path(current_user.id)}
                  Notifications
                  %span.badge= current_user.notifications.with_new_state.count
              %li
                = link_to "Home", root_path
              - if current_user.accountable_type == "Player"
                %li
                  = link_to "Schools", schools_path
              - else
                %li
                  = link_to "Players", players_path
              %li
                %a{href: logout_path} Logout
    - if current_user
      .col-md-1.gutter
      .col-md-1
      .col-md-8#body-view
        .container
          = yield
      .col-md-1
      .col-md-1.gutter
    - else
      .container#body-view
        = yield